/**
 * Dummy data standing in for the backend.
 *
 * Everything here is deterministic and static so the UI is reproducible.
 * Shapes match src/lib/types.ts exactly, so swapping in a real API means
 * replacing the functions in src/lib/api.ts and nothing else.
 */
import type {
  ApprovalPackage,
  GraphBuild,
  IngestJob,
  Project,
  Workspace,
  AuditEntry,
  ChatMessage,
  CostPoint,
  CycleTimePoint,
  DoraMetric,
  EnvironmentFingerprint,
  GraphEdge,
  GraphNode,
  ImpactAnalysis,
  KnowledgeSource,
  ModelSpend,
  RunPoint,
  RunTotals,
  Policy,
  Requirement,
  TestRun,
} from './types'

export const CURRENT_USER = {
  name: 'Sathish Kumar',
  email: 'sathish.kumar@acme.example',
  role: 'QA Lead',
  initials: 'SK',
}

const WORKDAY_ENV: EnvironmentFingerprint = {
  environment: 'Sandbox (Implementation)',
  tenant: 'acme_hcm_impl',
  release: 'Workday 2026R1',
  refreshedAt: '2026-07-14T02:00:00Z',
  dataCoverage: 41,
}

const SAP_ENV: EnvironmentFingerprint = {
  environment: 'Dev (D01)',
  tenant: 'sap-d01-100',
  release: 'S/4HANA 2025 FPS01',
  refreshedAt: '2026-08-01T22:30:00Z',
  dataCoverage: 63,
}

/* --------------------------------------------------------------- workspaces */

export const WORKSPACES: Workspace[] = [
  {
    id: 'ws-acme',
    name: 'Workspace 1',
    slug: 'acme-corp',
    compliance: ['SOX', 'GDPR'],
    region: 'EU / UK',
    memberCount: 48,
    projectIds: ['pj-hcm', 'pj-fin', 'pj-svc'],
  },
  {
    id: 'ws-northwind',
    name: 'Workspace 2',
    slug: 'northwind',
    compliance: ['GxP', 'HIPAA', 'SOX'],
    region: 'US',
    memberCount: 26,
    projectIds: ['pj-clin'],
  },
  {
    id: 'ws-sandbox',
    name: 'Workspace 3',
    slug: 'sandbox',
    compliance: [],
    region: 'Global',
    memberCount: 7,
    projectIds: ['pj-demo'],
  },
]

export const PROJECTS: Project[] = [
  {
    id: 'pj-hcm',
    workspaceId: 'ws-acme',
    name: 'Workday HCM',
    key: 'HCM',
    description: 'Absence, time tracking and payroll-adjacent configuration.',
    status: 'active',
    platform: 'Workday HCM',
    lead: 'M. Okafor',
    createdAt: '2026-01-14T09:00:00Z',
    sourceIds: ['src-wd', 'src-repo', 'src-conf', 'src-brd', 'src-figma', 'src-jira'],
    openRequirements: ['req-1', 'req-2', 'req-3', 'req-6'],
    monthlySpendUsd: 842.18,
  },
  {
    id: 'pj-fin',
    workspaceId: 'ws-acme',
    name: 'S/4HANA Finance',
    key: 'FIN',
    description: 'Vendor master, procurement thresholds and month-end close.',
    status: 'active',
    platform: 'SAP S/4HANA',
    lead: 'P. Novak',
    createdAt: '2026-02-03T09:00:00Z',
    sourceIds: ['src-sap', 'src-brd'],
    openRequirements: ['req-4'],
    monthlySpendUsd: 318.44,
  },
  {
    id: 'pj-svc',
    workspaceId: 'ws-acme',
    name: 'Field Service',
    key: 'SVC',
    description: 'Dynamics 365 work-order routing and technician scheduling.',
    status: 'paused',
    platform: 'Dynamics 365',
    lead: 'R. Mensah',
    createdAt: '2026-03-22T09:00:00Z',
    sourceIds: ['src-d365'],
    openRequirements: [],
    monthlySpendUsd: 0,
  },
  {
    id: 'pj-clin',
    workspaceId: 'ws-northwind',
    name: 'Clinical Systems',
    key: 'CLIN',
    description: 'GxP-validated modules; every change needs a validation window.',
    status: 'active',
    platform: 'Workday HCM',
    lead: 'D. Whitfield',
    createdAt: '2026-04-08T09:00:00Z',
    sourceIds: ['src-wd', 'src-conf'],
    openRequirements: ['req-5'],
    monthlySpendUsd: 124.9,
  },
  {
    id: 'pj-demo',
    workspaceId: 'ws-sandbox',
    name: 'Connector Trials',
    key: 'TRIAL',
    description: 'Throwaway project for evaluating new connectors.',
    status: 'planning',
    platform: 'Mixed',
    lead: 'Sathish Kumar',
    createdAt: '2026-07-30T09:00:00Z',
    sourceIds: [],
    openRequirements: [],
    monthlySpendUsd: 12.4,
  },
]

/* ------------------------------------------------------------------ sources */

export const SOURCES: KnowledgeSource[] = [
  {
    id: 'src-wd',
    name: 'Workday HCM — Production Tenant',
    kind: 'platform',
    provider: 'Workday',
    status: 'connected',
    lastSyncedAt: '2026-08-06T06:15:00Z',
    stalenessThresholdDays: 7,
    entities: 14382,
    documents: 0,
    coverage: 88,
    sizeLabel: '2.4 GB',
    owner: 'HR Systems',
  },
  {
    id: 'src-sap',
    name: 'SAP S/4HANA — Finance Config',
    kind: 'platform',
    provider: 'SAP',
    status: 'syncing',
    lastSyncedAt: '2026-08-05T19:40:00Z',
    stalenessThresholdDays: 7,
    entities: 38104,
    documents: 0,
    coverage: 71,
    sizeLabel: '9.1 GB',
    owner: 'Finance IT',
  },
  {
    id: 'src-repo',
    name: 'acme/integration-services',
    kind: 'repository',
    provider: 'GitHub',
    status: 'connected',
    lastSyncedAt: '2026-08-06T07:02:00Z',
    stalenessThresholdDays: 1,
    entities: 6721,
    documents: 143,
    coverage: 96,
    sizeLabel: '418 MB',
    owner: 'Platform Engineering',
  },
  {
    id: 'src-conf',
    name: 'Confluence — HR Transformation',
    kind: 'wiki',
    provider: 'Confluence',
    status: 'stale',
    lastSyncedAt: '2026-06-28T11:20:00Z',
    stalenessThresholdDays: 14,
    entities: 891,
    documents: 312,
    coverage: 64,
    sizeLabel: '96 MB',
    owner: 'HR Transformation PMO',
  },
  {
    id: 'src-brd',
    name: 'BRD / PRD Repository',
    kind: 'document',
    provider: 'SharePoint',
    status: 'connected',
    lastSyncedAt: '2026-08-04T14:00:00Z',
    stalenessThresholdDays: 30,
    entities: 402,
    documents: 87,
    coverage: 79,
    sizeLabel: '210 MB',
    owner: 'Business Analysis',
  },
  {
    id: 'src-figma',
    name: 'Figma — Employee Self-Service',
    kind: 'design',
    provider: 'Figma',
    status: 'connected',
    lastSyncedAt: '2026-08-03T09:12:00Z',
    stalenessThresholdDays: 30,
    entities: 268,
    documents: 12,
    coverage: 55,
    sizeLabel: '48 MB',
    owner: 'Product Design',
  },
  {
    id: 'src-jira',
    name: 'Jira — HRIS Delivery',
    kind: 'ticketing',
    provider: 'Jira',
    status: 'connected',
    lastSyncedAt: '2026-08-06T07:30:00Z',
    stalenessThresholdDays: 3,
    entities: 3244,
    documents: 0,
    coverage: 92,
    sizeLabel: '124 MB',
    owner: 'Delivery',
  },
  {
    id: 'src-d365',
    name: 'Dynamics 365 — Field Service',
    kind: 'platform',
    provider: 'Microsoft',
    status: 'error',
    lastSyncedAt: '2026-07-30T16:45:00Z',
    stalenessThresholdDays: 7,
    entities: 0,
    documents: 0,
    coverage: 0,
    sizeLabel: '—',
    owner: 'Service Ops',
    error: 'OAuth consent expired — admin re-consent required for Dataverse scope',
  },
]

/* ---------------------------------------------------------------- ingestion */

export const INGEST_JOBS: IngestJob[] = [
  {
    id: 'ing-1',
    projectId: 'pj-hcm',
    name: 'BRD-2025-HR-014.pdf',
    kind: 'document',
    docKind: 'brd',
    provider: 'Upload',
    stage: 'ready',
    progress: 100,
    sizeLabel: '4.2 MB',
    uploadedAt: '2026-08-04T14:02:00Z',
    uploadedBy: 'S. Iyer',
    entitiesExtracted: 62,
    linksProposed: 18,
    parseCoverage: 91,
    warnings: [],
  },
  {
    id: 'ing-2',
    projectId: 'pj-hcm',
    name: 'SRS-Absence-Management-v3.docx',
    kind: 'document',
    docKind: 'srs',
    provider: 'Upload',
    stage: 'needs_review',
    progress: 100,
    sizeLabel: '1.8 MB',
    uploadedAt: '2026-08-05T09:14:00Z',
    uploadedBy: 'S. Iyer',
    entitiesExtracted: 41,
    linksProposed: 9,
    parseCoverage: 68,
    message: '7 requirements reference a "Leave Engine" that matches no object in the estate.',
    warnings: [
      'Section 4 is a scanned image — 32% of the document could not be read',
      '7 extracted requirements have no candidate link',
    ],
  },
  {
    id: 'ing-3',
    projectId: 'pj-hcm',
    name: 'acme/integration-services',
    kind: 'repository',
    provider: 'GitHub',
    stage: 'ready',
    progress: 100,
    sizeLabel: '418 MB',
    uploadedAt: '2026-08-06T07:02:00Z',
    uploadedBy: 'Meridian Ingest',
    entitiesExtracted: 6721,
    linksProposed: 214,
    parseCoverage: 96,
    warnings: [],
  },
  {
    id: 'ing-4',
    projectId: 'pj-hcm',
    name: 'Workday HCM — Production Tenant',
    kind: 'platform',
    provider: 'Workday',
    stage: 'extracting',
    progress: 64,
    sizeLabel: '2.4 GB',
    uploadedAt: '2026-08-06T08:20:00Z',
    uploadedBy: 'Meridian Ingest',
    entitiesExtracted: 9140,
    linksProposed: 0,
    parseCoverage: 88,
    warnings: [],
  },
  {
    id: 'ing-5',
    projectId: 'pj-hcm',
    name: 'FRD-Overtime-Rules.pdf',
    kind: 'document',
    docKind: 'frd',
    provider: 'Upload',
    stage: 'linking',
    progress: 38,
    sizeLabel: '820 KB',
    uploadedAt: '2026-08-06T08:26:00Z',
    uploadedBy: 'Sathish Kumar',
    entitiesExtracted: 24,
    linksProposed: 6,
    parseCoverage: 94,
    warnings: [],
  },
  {
    id: 'ing-6',
    projectId: 'pj-hcm',
    name: 'Legacy-Payroll-Spec-1998.pdf',
    kind: 'document',
    docKind: 'other',
    provider: 'Upload',
    stage: 'failed',
    progress: 0,
    sizeLabel: '11.4 MB',
    uploadedAt: '2026-08-02T16:40:00Z',
    uploadedBy: 'P. Novak',
    entitiesExtracted: 0,
    linksProposed: 0,
    parseCoverage: 0,
    message: 'Encrypted PDF — Meridian cannot read password-protected files.',
    warnings: ['Remove the password and re-upload, or export an unprotected copy'],
  },
  {
    id: 'ing-7',
    projectId: 'pj-hcm',
    name: 'Employee-Self-Service-v4 (Figma)',
    kind: 'design',
    provider: 'Figma',
    stage: 'ready',
    progress: 100,
    sizeLabel: '48 MB',
    uploadedAt: '2026-08-03T09:12:00Z',
    uploadedBy: 'Meridian Ingest',
    entitiesExtracted: 268,
    linksProposed: 12,
    parseCoverage: 55,
    warnings: ['Frame names are the only join key available — links will be low confidence'],
  },
]

export const GRAPH_BUILD: GraphBuild = {
  id: 'build-14',
  projectId: 'pj-hcm',
  startedAt: '2026-08-06T08:12:00Z',
  finishedAt: '2026-08-06T08:31:00Z',
  status: 'complete',
  nodesCreated: 12,
  edgesProposed: 12,
  edgesConfirmed: 6,
  costUsd: 4.82,
  steps: [
    {
      id: 'st-1',
      label: 'Parse artefacts',
      description:
        'Text, structure and metadata lifted from every uploaded file and connected system.',
      status: 'done',
      detail: '7 artefacts · 1 failed',
      durationSeconds: 214,
      costUsd: 0.42,
    },
    {
      id: 'st-2',
      label: 'Extract entities',
      description:
        'Requirements, config objects, code symbols, screens and data entities identified.',
      status: 'done',
      detail: '16,256 entities',
      durationSeconds: 486,
      costUsd: 2.61,
    },
    {
      id: 'st-3',
      label: 'Resolve identities',
      description:
        'Deduplicate entities that appear in more than one artefact under different names.',
      status: 'done',
      detail: '1,284 merged',
      durationSeconds: 132,
      costUsd: 0.78,
    },
    {
      id: 'st-4',
      label: 'Propose links',
      description:
        'Score candidate relationships across artefacts. Each is a hypothesis, not a fact.',
      status: 'done',
      detail: '12 edges · 6 need review',
      durationSeconds: 298,
      costUsd: 1.01,
    },
    {
      id: 'st-5',
      label: 'Human confirmation',
      description: 'Low and medium confidence links stay unconfirmed until a person accepts them.',
      status: 'blocked',
      detail: '6 awaiting review',
      durationSeconds: 0,
      costUsd: 0,
    },
  ],
  unresolved: [
    {
      area: 'Figma → business process',
      reason: 'No traceable join key between frame names and business process definitions.',
      count: 7,
    },
    {
      area: 'SRS "Leave Engine"',
      reason: 'Referenced by 7 requirements but matches no object in the connected estate.',
      count: 7,
    },
    {
      area: 'Payroll provider (external)',
      reason: 'No connected source beyond the EIB boundary.',
      count: 1,
    },
  ],
}

/* -------------------------------------------------------------------- graph */

export const GRAPH_NODES: GraphNode[] = [
  {
    id: 'n-req-otp',
    label: 'Overtime Approval Policy',
    kind: 'policy',
    sourceId: 'src-brd',
    provenance: 'BRD-2025-HR-014.pdf § 3.1',
    sourceRef: 'sharepoint://brd/BRD-2025-HR-014.pdf#p12',
    criticality: 'critical',
    owner: 'HR Compliance',
    lastVerifiedAt: '2026-07-22T10:00:00Z',
    x: 0.14,
    y: 0.2,
    description:
      'Overtime above 8h/week requires dual approval by line manager and HR business partner.',
  },
  {
    id: 'n-bp-timeoff',
    label: 'Time Off & Absence',
    kind: 'business_process',
    sourceId: 'src-wd',
    provenance: 'Workday › Business Process › Time Off Request',
    sourceRef: 'workday://bp/time_off_request',
    criticality: 'critical',
    owner: 'HR Systems',
    lastVerifiedAt: '2026-08-01T08:00:00Z',
    x: 0.36,
    y: 0.12,
    description: 'End-to-end absence request, validation, approval routing and balance posting.',
  },
  {
    id: 'n-cfg-approval',
    label: 'BP Approval Chain — TIMEOFF_APPR',
    kind: 'config_object',
    sourceId: 'src-wd',
    provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
    sourceRef: 'workday://config/TIMEOFF_APPR',
    criticality: 'critical',
    owner: 'HR Systems',
    lastVerifiedAt: '2026-08-01T08:00:00Z',
    x: 0.58,
    y: 0.08,
    description: 'Approval step chain with 3 conditional routes and 1 escalation rule.',
  },
  {
    id: 'n-cfg-calc',
    label: 'Overtime Calculation — CALC_OT_STD',
    kind: 'config_object',
    sourceId: 'src-wd',
    provenance: 'Workday › Calculated Field › CALC_OT_STD',
    sourceRef: 'workday://config/CALC_OT_STD',
    criticality: 'critical',
    owner: 'Payroll',
    lastVerifiedAt: '2026-06-11T08:00:00Z',
    x: 0.58,
    y: 0.3,
    description: 'Derives payable overtime hours; consumed by payroll and by 3 reports.',
  },
  {
    id: 'n-int-payroll',
    label: 'Payroll Outbound Integration',
    kind: 'integration',
    sourceId: 'src-repo',
    provenance: 'src/integrations/payroll/outbound.ts:88',
    sourceRef: 'github://acme/integration-services/src/integrations/payroll/outbound.ts#L88',
    criticality: 'critical',
    owner: 'Platform Engineering',
    lastVerifiedAt: '2026-08-05T12:00:00Z',
    x: 0.8,
    y: 0.22,
    description: 'Nightly EIB pushing approved time + overtime to the payroll provider.',
  },
  {
    id: 'n-code-approval',
    label: 'ApprovalRouterService',
    kind: 'code_module',
    sourceId: 'src-repo',
    provenance: 'src/services/approval-router.ts:1',
    sourceRef: 'github://acme/integration-services/src/services/approval-router.ts',
    criticality: 'high',
    owner: 'Platform Engineering',
    lastVerifiedAt: '2026-08-05T12:00:00Z',
    x: 0.8,
    y: 0.46,
    description: 'Mirrors Workday approval routing for the self-service mobile app.',
  },
  {
    id: 'n-rpt-ot',
    label: 'Overtime Cost by Cost Centre',
    kind: 'report',
    sourceId: 'src-wd',
    provenance: 'Workday › Custom Report › RPT_OT_CC',
    sourceRef: 'workday://report/RPT_OT_CC',
    criticality: 'medium',
    owner: 'Finance IT',
    lastVerifiedAt: '2026-05-30T08:00:00Z',
    x: 0.36,
    y: 0.44,
    description: 'Monthly finance report consumed by 40+ cost centre managers.',
  },
  {
    id: 'n-scr-request',
    label: 'Request Time Off (Mobile)',
    kind: 'screen',
    sourceId: 'src-figma',
    provenance: 'Figma › ESS v4 › Frame "Request Time Off"',
    sourceRef: 'figma://file/ess-v4/node/122-455',
    criticality: 'medium',
    owner: 'Product Design',
    lastVerifiedAt: '2026-08-03T09:12:00Z',
    x: 0.14,
    y: 0.52,
    description: 'Employee-facing absence request screen, 3 states designed.',
  },
  {
    id: 'n-data-worker',
    label: 'Worker',
    kind: 'data_entity',
    sourceId: 'src-wd',
    provenance: 'Workday › Business Object › Worker',
    sourceRef: 'workday://object/Worker',
    criticality: 'critical',
    owner: 'HR Systems',
    lastVerifiedAt: '2026-08-01T08:00:00Z',
    x: 0.58,
    y: 0.62,
    description: 'Core worker record; 214 downstream references across the estate.',
  },
  {
    id: 'n-req-sox',
    label: 'SOX ITGC — Change Control',
    kind: 'policy',
    sourceId: 'src-conf',
    provenance: 'Confluence › Compliance › SOX ITGC Matrix',
    sourceRef: 'confluence://space/COMP/page/sox-itgc',
    criticality: 'critical',
    owner: 'Internal Audit',
    lastVerifiedAt: '2026-04-18T10:00:00Z',
    x: 0.14,
    y: 0.78,
    description:
      'Any change touching payroll-relevant calculation requires segregated approval + evidence.',
  },
  {
    id: 'n-int-ldap',
    label: 'Identity Sync (SCIM)',
    kind: 'integration',
    sourceId: 'src-repo',
    provenance: 'src/integrations/scim/sync.ts:34',
    sourceRef: 'github://acme/integration-services/src/integrations/scim/sync.ts#L34',
    criticality: 'high',
    owner: 'Platform Engineering',
    lastVerifiedAt: '2026-08-05T12:00:00Z',
    x: 0.8,
    y: 0.7,
    description: 'Provisions manager hierarchy used by approval routing.',
  },
  {
    id: 'n-rpt-audit',
    label: 'Approval Audit Extract',
    kind: 'report',
    sourceId: 'src-wd',
    provenance: 'Workday › Custom Report › RPT_APPR_AUDIT',
    sourceRef: 'workday://report/RPT_APPR_AUDIT',
    criticality: 'high',
    owner: 'Internal Audit',
    lastVerifiedAt: '2026-07-02T08:00:00Z',
    x: 0.36,
    y: 0.74,
    description: 'Quarterly evidence extract used directly in SOX walkthroughs.',
  },
]

export const GRAPH_EDGES: GraphEdge[] = [
  {
    id: 'e1',
    from: 'n-req-otp',
    to: 'n-bp-timeoff',
    label: 'governs',
    confidence: 'confirmed',
    confirmedBy: 'S. Iyer (BA)',
    confirmedAt: '2026-07-22T10:00:00Z',
    rationale: 'BRD section explicitly names the Time Off business process.',
  },
  {
    id: 'e2',
    from: 'n-bp-timeoff',
    to: 'n-cfg-approval',
    label: 'implemented by',
    confidence: 'confirmed',
    confirmedBy: 'M. Okafor (HR Systems)',
    confirmedAt: '2026-08-01T08:00:00Z',
    rationale: 'Direct Workday metadata reference.',
  },
  {
    id: 'e3',
    from: 'n-bp-timeoff',
    to: 'n-cfg-calc',
    label: 'uses',
    confidence: 'confirmed',
    confirmedBy: 'M. Okafor (HR Systems)',
    confirmedAt: '2026-08-01T08:00:00Z',
    rationale: 'Calculated field bound to the BP step.',
  },
  {
    id: 'e4',
    from: 'n-cfg-calc',
    to: 'n-int-payroll',
    label: 'feeds',
    confidence: 'high',
    confirmedBy: null,
    confirmedAt: null,
    rationale: 'Field name CALC_OT_STD appears in the integration payload mapping.',
  },
  {
    id: 'e5',
    from: 'n-cfg-approval',
    to: 'n-code-approval',
    label: 'mirrored by',
    confidence: 'medium',
    confirmedBy: null,
    confirmedAt: null,
    rationale:
      'Routing rules in code are structurally similar but were authored separately — needs confirmation.',
  },
  {
    id: 'e6',
    from: 'n-cfg-calc',
    to: 'n-rpt-ot',
    label: 'reported by',
    confidence: 'high',
    confirmedBy: null,
    confirmedAt: null,
    rationale: 'Report definition references the calculated field.',
  },
  {
    id: 'e7',
    from: 'n-scr-request',
    to: 'n-bp-timeoff',
    label: 'triggers',
    confidence: 'low',
    confirmedBy: null,
    confirmedAt: null,
    rationale:
      'Inferred from frame naming only. No traceable link between Figma and the BP definition.',
  },
  {
    id: 'e8',
    from: 'n-cfg-approval',
    to: 'n-data-worker',
    label: 'reads',
    confidence: 'confirmed',
    confirmedBy: 'M. Okafor (HR Systems)',
    confirmedAt: '2026-08-01T08:00:00Z',
    rationale: 'Manager hierarchy resolved from Worker.',
  },
  {
    id: 'e9',
    from: 'n-req-sox',
    to: 'n-cfg-calc',
    label: 'controls',
    confidence: 'confirmed',
    confirmedBy: 'D. Whitfield (Internal Audit)',
    confirmedAt: '2026-04-18T10:00:00Z',
    rationale: 'Named as payroll-relevant in the ITGC matrix.',
  },
  {
    id: 'e10',
    from: 'n-int-ldap',
    to: 'n-data-worker',
    label: 'provisions',
    confidence: 'high',
    confirmedBy: null,
    confirmedAt: null,
    rationale: 'SCIM mapping writes manager attribute on Worker.',
  },
  {
    id: 'e11',
    from: 'n-cfg-approval',
    to: 'n-rpt-audit',
    label: 'evidenced by',
    confidence: 'medium',
    confirmedBy: null,
    confirmedAt: null,
    rationale: 'Report filters on BP definition ID; binding not verified since 2026R1.',
  },
  {
    id: 'e12',
    from: 'n-req-sox',
    to: 'n-rpt-audit',
    label: 'requires',
    confidence: 'confirmed',
    confirmedBy: 'D. Whitfield (Internal Audit)',
    confirmedAt: '2026-04-18T10:00:00Z',
    rationale: 'Control test step names this extract.',
  },
]

/* ------------------------------------------------------------- requirements */

export const REQUIREMENTS: Requirement[] = [
  {
    id: 'req-1',
    ref: 'MER-1042',
    title: 'Auto-approve overtime under 4 hours per week',
    summary:
      'Reduce manager workload by auto-approving small overtime requests without changing payroll outcomes.',
    stage: 'awaiting_approval',
    requestedBy: 'J. Almeida',
    requestedByRole: 'VP People Operations',
    createdAt: '2026-08-01T09:20:00Z',
    updatedAt: '2026-08-06T07:45:00Z',
    platform: 'Workday HCM',
    systemKind: 'vendor_platform',
    priority: 'high',
    impactedNodeIds: ['n-cfg-approval', 'n-cfg-calc', 'n-int-payroll', 'n-rpt-ot', 'n-rpt-audit'],
    estimatedCostUsd: 41.8,
    actualCostUsd: 38.12,
    riskLevel: 'high',
  },
  {
    id: 'req-2',
    ref: 'MER-1039',
    title: 'Add cost centre dimension to absence reporting',
    summary: 'Finance needs absence cost split by cost centre for the quarterly review.',
    stage: 'evidence',
    requestedBy: 'K. Tan',
    requestedByRole: 'Finance Director',
    createdAt: '2026-07-28T13:05:00Z',
    updatedAt: '2026-08-05T16:22:00Z',
    platform: 'Workday HCM',
    systemKind: 'vendor_platform',
    priority: 'medium',
    impactedNodeIds: ['n-rpt-ot', 'n-cfg-calc'],
    estimatedCostUsd: 12.4,
    actualCostUsd: 11.05,
    riskLevel: 'low',
  },
  {
    id: 'req-3',
    ref: 'MER-1051',
    title: 'Mobile push notification for pending approvals',
    summary: 'Managers miss approvals; add push via the existing self-service app.',
    stage: 'impact_review',
    requestedBy: 'J. Almeida',
    requestedByRole: 'VP People Operations',
    createdAt: '2026-08-05T10:11:00Z',
    updatedAt: '2026-08-06T08:02:00Z',
    platform: 'Workday HCM + Mobile',
    systemKind: 'mixed',
    priority: 'high',
    impactedNodeIds: ['n-code-approval', 'n-cfg-approval', 'n-scr-request'],
    estimatedCostUsd: 22.6,
    actualCostUsd: 9.4,
    riskLevel: 'medium',
  },
  {
    id: 'req-4',
    ref: 'MER-1028',
    title: 'Vendor master approval threshold change',
    summary: 'Raise the auto-approval threshold for vendor master updates from $1k to $5k.',
    stage: 'rejected',
    requestedBy: 'P. Novak',
    requestedByRole: 'Procurement Lead',
    createdAt: '2026-07-19T08:40:00Z',
    updatedAt: '2026-07-21T15:30:00Z',
    platform: 'SAP S/4HANA',
    systemKind: 'vendor_platform',
    priority: 'critical',
    impactedNodeIds: ['n-req-sox'],
    estimatedCostUsd: 8.2,
    actualCostUsd: 8.2,
    riskLevel: 'critical',
  },
  {
    id: 'req-5',
    ref: 'MER-1017',
    title: 'Quarterly SOX evidence extract automation',
    summary: 'Generate the approval audit extract automatically at quarter end.',
    stage: 'signed_off',
    requestedBy: 'D. Whitfield',
    requestedByRole: 'Internal Audit',
    createdAt: '2026-07-02T11:00:00Z',
    updatedAt: '2026-07-24T09:15:00Z',
    platform: 'Workday HCM',
    systemKind: 'vendor_platform',
    priority: 'medium',
    impactedNodeIds: ['n-rpt-audit', 'n-cfg-approval'],
    estimatedCostUsd: 31.5,
    actualCostUsd: 29.87,
    riskLevel: 'medium',
  },
  {
    id: 'req-6',
    ref: 'MER-1055',
    title: 'Shift differential for weekend on-call',
    summary: 'Introduce a weekend differential rate for on-call engineers.',
    stage: 'discussing',
    requestedBy: 'R. Mensah',
    requestedByRole: 'Engineering Director',
    createdAt: '2026-08-06T06:50:00Z',
    updatedAt: '2026-08-06T08:14:00Z',
    platform: 'Crew Scheduler (internal)',
    systemKind: 'internal_project',
    priority: 'low',
    impactedNodeIds: ['n-cfg-calc', 'n-int-payroll'],
    estimatedCostUsd: 0,
    actualCostUsd: 3.15,
    riskLevel: 'high',
  },
]

/* ---------------------------------------------------------------- chat */

export const CHAT_THREAD: Record<string, ChatMessage[]> = {
  'req-1': [
    {
      id: 'm1',
      role: 'user',
      at: '2026-08-01T09:20:00Z',
      content:
        'Our managers are drowning in overtime approvals. Most of them are tiny — an hour here or there. Can we just auto-approve anything under 4 hours a week?',
    },
    {
      id: 'm2',
      role: 'assistant',
      at: '2026-08-01T09:20:38Z',
      model: 'claude-opus-5',
      tokensIn: 18420,
      tokensOut: 962,
      costUsd: 0.41,
      content:
        'I can see what you are describing. Against your current configuration, 68% of overtime requests in the last 90 days were under 4 hours, so the workload reduction would be real.\n\nBefore we go further there is a conflict I need to raise, because it changes what we can actually build.',
      citations: [
        {
          nodeId: 'n-cfg-approval',
          label: 'BP Approval Chain — TIMEOFF_APPR',
          provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
          confidence: 'confirmed',
        },
        {
          nodeId: 'n-bp-timeoff',
          label: 'Time Off & Absence',
          provenance: 'Workday › Business Process › Time Off Request',
          confidence: 'confirmed',
        },
      ],
      dissent: {
        severity: 'blocking',
        statement:
          'This request contradicts an existing control. BRD-2025-HR-014 § 3.1 requires dual approval for overtime above 8h/week, and the SOX ITGC matrix classifies overtime calculation as payroll-relevant. Auto-approval below 4h does not breach the 8h rule directly, but removing the manager step also removes the only recorded approval event that the quarterly audit extract depends on.',
        conflictsWith: 'SOX ITGC — Change Control',
      },
    },
    {
      id: 'm3',
      role: 'user',
      at: '2026-08-01T09:24:10Z',
      content:
        'I did not know the audit extract depended on that. Is there a version of this that keeps the auditors happy?',
    },
    {
      id: 'm4',
      role: 'assistant',
      at: '2026-08-01T09:24:52Z',
      model: 'claude-opus-5',
      tokensIn: 21050,
      tokensOut: 1340,
      costUsd: 0.58,
      content:
        'Yes. Three options, in order of how much I would recommend them:\n\n**1. System-actioned approval (recommended).** Keep the approval step but let a system account auto-action it below the threshold. The approval event still exists, so RPT_APPR_AUDIT keeps working unchanged, and the audit trail shows an explicit automated decision rather than a missing one.\n\n**2. Bypass with compensating log.** Remove the step and write a synthetic record to a custom object. Cheaper to configure, but you are now maintaining audit evidence outside the system of record — Internal Audit has historically rejected this pattern.\n\n**3. Threshold in the calculation.** Change CALC_OT_STD so sub-4h does not classify as overtime at all. I would advise against this: it changes payroll output, not just routing, and it would affect the three reports downstream.\n\nOption 1 touches routing only and leaves payroll figures identical.',
      citations: [
        {
          nodeId: 'n-cfg-approval',
          label: 'BP Approval Chain — TIMEOFF_APPR',
          provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
          confidence: 'confirmed',
        },
        {
          nodeId: 'n-rpt-audit',
          label: 'Approval Audit Extract',
          provenance: 'Workday › Custom Report › RPT_APPR_AUDIT',
          confidence: 'medium',
        },
        {
          nodeId: 'n-cfg-calc',
          label: 'Overtime Calculation — CALC_OT_STD',
          provenance: 'Workday › Calculated Field › CALC_OT_STD',
          confidence: 'confirmed',
        },
        {
          nodeId: 'n-req-sox',
          label: 'SOX ITGC — Change Control',
          provenance: 'Confluence › Compliance › SOX ITGC Matrix',
          confidence: 'confirmed',
        },
      ],
    },
    {
      id: 'm5',
      role: 'user',
      at: '2026-08-01T09:31:02Z',
      content: 'Option 1. Let us go with that. What happens next?',
    },
    {
      id: 'm6',
      role: 'assistant',
      at: '2026-08-01T09:31:40Z',
      model: 'claude-opus-5',
      tokensIn: 23110,
      tokensOut: 780,
      costUsd: 0.34,
      content:
        "Agreed — I have recorded option 1 as the accepted approach.\n\nI have run an impact analysis against your Workday sandbox. It found **5 impacted objects**, one of which has no regression coverage today. I have also flagged one blind spot: I cannot see the payroll provider's side of the outbound integration, so I cannot prove downstream behaviour beyond the EIB boundary.\n\nReview the impact analysis and I will generate the regression suite from there.",
      citations: [
        {
          nodeId: 'n-int-payroll',
          label: 'Payroll Outbound Integration',
          provenance: 'src/integrations/payroll/outbound.ts:88',
          confidence: 'high',
        },
      ],
    },
  ],
}

/* -------------------------------------------------------------- impact */

export const IMPACT_ANALYSES: Record<string, ImpactAnalysis> = {
  'req-1': {
    requirementId: 'req-1',
    generatedAt: '2026-08-01T09:31:20Z',
    model: 'claude-opus-5',
    costUsd: 2.86,
    durationSeconds: 94,
    environmentFingerprint: WORKDAY_ENV,
    items: [
      {
        id: 'imp-1',
        nodeId: 'n-cfg-approval',
        nodeLabel: 'BP Approval Chain — TIMEOFF_APPR',
        nodeKind: 'config_object',
        severity: 'breaking',
        confidence: 'confirmed',
        reason:
          'A new conditional route must be inserted before step 2. Existing route ordering shifts, which invalidates the cached step indices used by two integrations.',
        provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
        owner: 'HR Systems',
        coveredByTestIds: ['run-1', 'run-2'],
        coverageGap: false,
      },
      {
        id: 'imp-2',
        nodeId: 'n-rpt-audit',
        nodeLabel: 'Approval Audit Extract',
        nodeKind: 'report',
        severity: 'major',
        confidence: 'medium',
        reason:
          'Extract filters on approver type = Human. System-actioned approvals will be excluded unless the filter is widened.',
        provenance: 'Workday › Custom Report › RPT_APPR_AUDIT',
        owner: 'Internal Audit',
        coveredByTestIds: [],
        coverageGap: true,
      },
      {
        id: 'imp-3',
        nodeId: 'n-int-payroll',
        nodeLabel: 'Payroll Outbound Integration',
        nodeKind: 'integration',
        severity: 'minor',
        confidence: 'high',
        reason:
          'Payload unchanged, but approval timestamp distribution shifts earlier. Downstream SLA report may show an artificial improvement.',
        provenance: 'src/integrations/payroll/outbound.ts:88',
        owner: 'Platform Engineering',
        coveredByTestIds: ['run-3'],
        coverageGap: false,
      },
      {
        id: 'imp-4',
        nodeId: 'n-code-approval',
        nodeLabel: 'ApprovalRouterService',
        nodeKind: 'code_module',
        severity: 'major',
        confidence: 'medium',
        reason:
          'The mobile app mirrors routing logic independently. If it is not updated in the same release, mobile and web will disagree about whether an item needs action.',
        provenance: 'src/services/approval-router.ts:1',
        owner: 'Platform Engineering',
        coveredByTestIds: ['run-4'],
        coverageGap: false,
      },
      {
        id: 'imp-5',
        nodeId: 'n-rpt-ot',
        nodeLabel: 'Overtime Cost by Cost Centre',
        nodeKind: 'report',
        severity: 'none',
        confidence: 'high',
        reason:
          'Reads CALC_OT_STD, which is unchanged under the selected option. No expected impact.',
        provenance: 'Workday › Custom Report › RPT_OT_CC',
        owner: 'Finance IT',
        coveredByTestIds: ['run-5'],
        coverageGap: false,
      },
    ],
    blindSpots: [
      {
        area: 'Payroll provider (external)',
        reason:
          'No connected source beyond the EIB boundary. Behaviour after the outbound push cannot be analysed or tested.',
      },
      {
        area: 'Confluence HR space',
        reason:
          'Source is stale (39 days). Any policy amended after 2026-06-28 is not reflected in this analysis.',
      },
    ],
  },

  'req-2': {
    requirementId: 'req-2',
    generatedAt: '2026-07-28T13:40:05Z',
    model: 'claude-opus-5',
    costUsd: 0.94,
    durationSeconds: 38,
    environmentFingerprint: WORKDAY_ENV,
    items: [
      {
        id: 'imp-2-1',
        nodeId: 'n-rpt-ot',
        nodeLabel: 'Overtime Cost by Cost Centre',
        nodeKind: 'report',
        severity: 'major',
        confidence: 'confirmed',
        reason:
          'A new grouping dimension is added to the report definition. Saved views pinned to the old column order will render the dimension in an unexpected position.',
        provenance: 'Workday › Custom Report › RPT_OT_CC',
        owner: 'Finance IT',
        coveredByTestIds: ['run-5'],
        coverageGap: false,
      },
      {
        id: 'imp-2-2',
        nodeId: 'n-cfg-calc',
        nodeLabel: 'Overtime Calculation — CALC_OT_STD',
        nodeKind: 'config_object',
        severity: 'none',
        confidence: 'confirmed',
        reason:
          'Read-only dependency. The calculated field is referenced but not modified, so totals are unaffected.',
        provenance: 'Workday › Calculated Field › CALC_OT_STD',
        owner: 'HR Systems',
        coveredByTestIds: ['run-5'],
        coverageGap: false,
      },
    ],
    blindSpots: [
      {
        area: 'Cost centre hierarchy source',
        reason:
          'The hierarchy is mastered in the finance ERP, which is not a connected source. Mid-period reorganisations cannot be reasoned about here.',
      },
    ],
  },

  'req-3': {
    requirementId: 'req-3',
    generatedAt: '2026-08-06T08:12:44Z',
    model: 'claude-opus-5',
    costUsd: 1.62,
    durationSeconds: 61,
    environmentFingerprint: WORKDAY_ENV,
    items: [
      {
        id: 'imp-3-1',
        nodeId: 'n-code-approval',
        nodeLabel: 'ApprovalRouterService',
        nodeKind: 'code_module',
        severity: 'breaking',
        confidence: 'high',
        reason:
          'Push delivery needs a per-item "requiresAction" flag the router does not currently emit. Adding it changes the shape of a response three clients already consume.',
        provenance: 'src/services/approval-router.ts:1',
        owner: 'Platform Engineering',
        coveredByTestIds: [],
        coverageGap: true,
      },
      {
        id: 'imp-3-2',
        nodeId: 'n-scr-request',
        nodeLabel: 'Request Time Off (Mobile)',
        nodeKind: 'screen',
        severity: 'major',
        confidence: 'medium',
        reason:
          'The mobile approval list is rendered from a cached payload. Without cache invalidation on push receipt, the notification will point at an item the list still shows as pending.',
        provenance: 'Figma › Mobile ESS › Approvals v4',
        owner: 'Mobile Engineering',
        coveredByTestIds: [],
        coverageGap: true,
      },
      {
        id: 'imp-3-3',
        nodeId: 'n-cfg-approval',
        nodeLabel: 'BP Approval Chain — TIMEOFF_APPR',
        nodeKind: 'config_object',
        severity: 'minor',
        confidence: 'confirmed',
        reason:
          'No routing change. The chain is read to determine who should receive a notification, not modified.',
        provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
        owner: 'HR Systems',
        coveredByTestIds: ['run-1'],
        coverageGap: false,
      },
    ],
    blindSpots: [
      {
        area: 'Push notification provider',
        reason:
          'Delivery is handled by an external APNs/FCM relay with no connected source. Delivery failures cannot be observed from here.',
      },
      {
        area: 'Mobile app release cadence',
        reason:
          'The mobile client ships on its own schedule. This analysis cannot confirm that a compatible client version will be live when the backend change lands.',
      },
    ],
  },

  'req-4': {
    requirementId: 'req-4',
    generatedAt: '2026-07-19T10:05:11Z',
    model: 'claude-opus-5',
    costUsd: 1.18,
    durationSeconds: 44,
    environmentFingerprint: SAP_ENV,
    items: [
      {
        id: 'imp-4-1',
        nodeId: 'n-req-sox',
        nodeLabel: 'SOX ITGC — Change Control',
        nodeKind: 'policy',
        severity: 'breaking',
        confidence: 'confirmed',
        reason:
          'Raising the vendor master approval threshold removes a second-approver step that the SOX control matrix names explicitly as a key control. The change cannot proceed without a control redesign signed by the control owner.',
        provenance: 'Confluence › Compliance › SOX ITGC Matrix',
        owner: 'Internal Audit',
        coveredByTestIds: [],
        coverageGap: true,
      },
    ],
    blindSpots: [
      {
        area: 'External auditor position',
        reason:
          'Whether the redesigned control would be accepted at year-end is a judgement no connected system can answer.',
      },
    ],
  },

  'req-5': {
    requirementId: 'req-5',
    generatedAt: '2026-06-30T15:22:48Z',
    model: 'claude-opus-5',
    costUsd: 1.05,
    durationSeconds: 40,
    environmentFingerprint: WORKDAY_ENV,
    items: [
      {
        id: 'imp-5-1',
        nodeId: 'n-rpt-audit',
        nodeLabel: 'Approval Audit Extract',
        nodeKind: 'report',
        severity: 'major',
        confidence: 'confirmed',
        reason:
          'The extract becomes a scheduled job rather than a manual run. Its output contract is unchanged, but failure now needs to alert rather than simply not happen.',
        provenance: 'Workday › Custom Report › RPT_APPR_AUDIT',
        owner: 'Internal Audit',
        coveredByTestIds: ['run-2'],
        coverageGap: false,
      },
      {
        id: 'imp-5-2',
        nodeId: 'n-cfg-approval',
        nodeLabel: 'BP Approval Chain — TIMEOFF_APPR',
        nodeKind: 'config_object',
        severity: 'none',
        confidence: 'confirmed',
        reason: 'Read as a data source for the extract. Not modified.',
        provenance: 'Workday › BP Definition › TIMEOFF_APPR (v14)',
        owner: 'HR Systems',
        coveredByTestIds: ['run-1'],
        coverageGap: false,
      },
    ],
    blindSpots: [],
  },
}

/* ------------------------------------------------------------- evidence */

export const TEST_RUNS: TestRun[] = [
  {
    id: 'run-1',
    ref: 'EV-3301',
    requirementId: 'req-1',
    title: 'Overtime under 4h is auto-approved and records a system approval event',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/timeoff/approval-routing.spec.ts',
    startedAt: '2026-08-05T14:02:00Z',
    durationSeconds: 168,
    attempts: 1,
    flakeRate: 0,
    runner: 'Playwright 1.52 · chromium',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-cfg-approval'],
    costUsd: 0.42,
    artifacts: [
      { id: 'a1', kind: 'video', label: 'run.webm', sizeLabel: '4.2 MB', sha256: '9f2c41e8a7b3' },
      { id: 'a2', kind: 'trace', label: 'trace.zip', sizeLabel: '1.8 MB', sha256: '3d81ff0ac214' },
      { id: 'a3', kind: 'network', label: 'har.json', sizeLabel: '640 KB', sha256: 'c07be5519d3a' },
      {
        id: 'a4',
        kind: 'dom',
        label: 'dom-final.html',
        sizeLabel: '212 KB',
        sha256: '55ab9127ee60',
      },
    ],
  },
  {
    id: 'run-2',
    ref: 'EV-3302',
    requirementId: 'req-1',
    title: 'Overtime above 8h still requires dual approval',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/timeoff/approval-routing.spec.ts',
    startedAt: '2026-08-05T14:05:00Z',
    durationSeconds: 204,
    attempts: 1,
    flakeRate: 0,
    runner: 'Playwright 1.52 · chromium',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-cfg-approval', 'n-req-otp'],
    costUsd: 0.51,
    artifacts: [
      { id: 'a5', kind: 'video', label: 'run.webm', sizeLabel: '5.1 MB', sha256: '77e1b0c4a992' },
      { id: 'a6', kind: 'trace', label: 'trace.zip', sizeLabel: '2.1 MB', sha256: 'ba33c9de1f45' },
    ],
  },
  {
    id: 'run-3',
    ref: 'EV-3303',
    requirementId: 'req-1',
    title: 'Payroll EIB payload is byte-identical before and after the change',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/integrations/payroll-eib.spec.ts',
    startedAt: '2026-08-05T14:11:00Z',
    durationSeconds: 342,
    attempts: 2,
    flakeRate: 0.08,
    runner: 'Playwright 1.52 · api',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-int-payroll'],
    costUsd: 0.88,
    artifacts: [
      { id: 'a7', kind: 'log', label: 'diff.txt', sizeLabel: '18 KB', sha256: 'e91a7742bd08' },
      { id: 'a8', kind: 'network', label: 'har.json', sizeLabel: '1.2 MB', sha256: '2c5f8830ab71' },
    ],
  },
  {
    id: 'run-4',
    ref: 'EV-3304',
    requirementId: 'req-1',
    title: 'Mobile approval list matches web after routing change',
    grade: 'verified',
    status: 'failed',
    suite: 'regression/mobile/approval-parity.spec.ts',
    startedAt: '2026-08-05T14:19:00Z',
    durationSeconds: 96,
    attempts: 3,
    flakeRate: 0.12,
    runner: 'Playwright 1.52 · webkit',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-code-approval'],
    failureReason:
      'ApprovalRouterService still returns requiresAction=true for sub-4h items. Mobile shows 12 items, web shows 0.',
    costUsd: 0.36,
    artifacts: [
      { id: 'a9', kind: 'video', label: 'run.webm', sizeLabel: '3.4 MB', sha256: '61bd0e9c3357' },
      {
        id: 'a10',
        kind: 'screenshot',
        label: 'failure.png',
        sizeLabel: '284 KB',
        sha256: 'af772901ce6b',
      },
      { id: 'a11', kind: 'trace', label: 'trace.zip', sizeLabel: '1.4 MB', sha256: '0e4c81aa5d29' },
    ],
  },
  {
    id: 'run-5',
    ref: 'EV-3305',
    requirementId: 'req-1',
    title: 'Overtime cost report totals unchanged',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/reports/ot-cost.spec.ts',
    startedAt: '2026-08-05T14:24:00Z',
    durationSeconds: 121,
    attempts: 1,
    flakeRate: 0,
    runner: 'Playwright 1.52 · chromium',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-rpt-ot'],
    costUsd: 0.29,
    artifacts: [
      {
        id: 'a12',
        kind: 'screenshot',
        label: 'report.png',
        sizeLabel: '198 KB',
        sha256: '8b12ff40e7c5',
      },
    ],
  },
  {
    id: 'run-6',
    ref: 'EV-3306',
    requirementId: 'req-1',
    title: 'Audit extract still captures auto-approved records',
    grade: 'asserted',
    status: 'passed',
    suite: null,
    startedAt: '2026-08-05T14:31:00Z',
    durationSeconds: 58,
    attempts: 1,
    flakeRate: 0,
    runner: 'Browser agent · claude-opus-5',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-rpt-audit'],
    costUsd: 1.24,
    artifacts: [
      {
        id: 'a13',
        kind: 'screenshot',
        label: 'agent-final.png',
        sizeLabel: '310 KB',
        sha256: 'd4471a02b88f',
      },
      {
        id: 'a14',
        kind: 'log',
        label: 'agent-transcript.md',
        sizeLabel: '42 KB',
        sha256: '19cc7e6055ad',
      },
    ],
  },
  {
    id: 'run-7',
    ref: 'EV-3290',
    requirementId: 'req-2',
    title: 'Cost centre column renders for all 40 cost centres',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/reports/absence-cc.spec.ts',
    startedAt: '2026-08-05T11:12:00Z',
    durationSeconds: 88,
    attempts: 1,
    flakeRate: 0,
    runner: 'Playwright 1.52 · chromium',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-rpt-ot'],
    costUsd: 0.22,
    artifacts: [
      {
        id: 'a15',
        kind: 'screenshot',
        label: 'report.png',
        sizeLabel: '224 KB',
        sha256: '6fa1cc3390b2',
      },
    ],
  },
  {
    id: 'run-8',
    ref: 'EV-3291',
    requirementId: 'req-2',
    title: 'Report export completes under 30s at full volume',
    grade: 'verified',
    status: 'flaky',
    suite: 'regression/reports/absence-cc.spec.ts',
    startedAt: '2026-08-05T11:16:00Z',
    durationSeconds: 271,
    attempts: 3,
    flakeRate: 0.34,
    runner: 'Playwright 1.52 · chromium',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-rpt-ot'],
    failureReason: 'Passed on attempt 3. Export timing varies 18s–41s depending on sandbox load.',
    costUsd: 0.61,
    artifacts: [
      { id: 'a16', kind: 'trace', label: 'trace.zip', sizeLabel: '2.8 MB', sha256: 'cc90ab7712de' },
    ],
  },
  {
    id: 'run-9',
    ref: 'EV-3310',
    requirementId: 'req-3',
    title: 'Push notification fires within 60s of approval assignment',
    grade: 'asserted',
    status: 'running',
    suite: null,
    startedAt: '2026-08-06T08:10:00Z',
    durationSeconds: 0,
    attempts: 1,
    flakeRate: 0,
    runner: 'Browser agent · claude-opus-5',
    environment: WORKDAY_ENV,
    coveredNodeIds: ['n-code-approval'],
    costUsd: 0.18,
    artifacts: [],
  },
  {
    id: 'run-10',
    ref: 'EV-3250',
    requirementId: 'req-5',
    title: 'Quarterly extract generates with correct period boundaries',
    grade: 'verified',
    status: 'passed',
    suite: 'regression/reports/sox-extract.spec.ts',
    startedAt: '2026-07-23T09:40:00Z',
    durationSeconds: 402,
    attempts: 1,
    flakeRate: 0,
    runner: 'Playwright 1.52 · chromium',
    environment: SAP_ENV,
    coveredNodeIds: ['n-rpt-audit'],
    costUsd: 0.94,
    artifacts: [
      { id: 'a17', kind: 'video', label: 'run.webm', sizeLabel: '8.1 MB', sha256: '3a77e10bb492' },
      { id: 'a18', kind: 'trace', label: 'trace.zip', sizeLabel: '3.2 MB', sha256: 'f01c2b8a7734' },
    ],
  },
]

/* ------------------------------------------------------------- approvals */

export const APPROVAL_PACKAGES: ApprovalPackage[] = [
  {
    id: 'ap-1',
    requirementId: 'req-1',
    requirementRef: 'MER-1042',
    title: 'Auto-approve overtime under 4 hours per week',
    submittedAt: '2026-08-05T15:00:00Z',
    submittedBy: 'S. Iyer (BA)',
    estimatedCostUsd: 41.8,
    riskLevel: 'high',
    evidenceSummary: { verified: 4, asserted: 1, failed: 1, coverageGaps: 1 },
    gates: [
      {
        id: 'g1',
        name: 'Business Owner',
        role: 'VP People Operations',
        requiresEvidenceGrade: null,
        decision: 'approved',
        approver: 'J. Almeida',
        approverEmail: 'j.almeida@acme.example',
        decidedAt: '2026-08-05T16:12:00Z',
        comment: 'Approach agreed. Option 1 keeps the audit trail intact.',
        blockedBy: [],
        dueAt: '2026-08-04T17:00:00Z',
      },
      {
        id: 'g2',
        name: 'Platform Owner',
        role: 'HR Systems',
        requiresEvidenceGrade: 'verified',
        decision: 'approved',
        approver: 'M. Okafor',
        approverEmail: 'm.okafor@acme.example',
        decidedAt: '2026-08-05T17:40:00Z',
        comment: 'Routing change is contained. Reviewed the trace artifacts.',
        blockedBy: [],
        dueAt: '2026-08-05T17:00:00Z',
      },
      {
        id: 'g3',
        name: 'Internal Audit',
        role: 'SOX Control Owner',
        requiresEvidenceGrade: 'verified',
        decision: 'pending',
        approver: null,
        approverEmail: null,
        decidedAt: null,
        comment: null,
        blockedBy: [
          'POL-004: payroll-relevant change requires verified evidence on every impacted node — RPT_APPR_AUDIT has no regression coverage',
          'EV-3306 is asserted, not verified — cannot satisfy this gate',
        ],
        dueAt: '2026-08-06T01:50:00Z',
      },
      {
        id: 'g4',
        name: 'Release Manager',
        role: 'Change Advisory Board',
        requiresEvidenceGrade: 'verified',
        decision: 'pending',
        approver: null,
        approverEmail: null,
        decidedAt: null,
        comment: null,
        blockedBy: ['EV-3304 failed — mobile/web approval parity broken'],
        dueAt: '2026-08-06T17:35:00Z',
      },
    ],
  },
  {
    id: 'ap-2',
    requirementId: 'req-2',
    requirementRef: 'MER-1039',
    title: 'Add cost centre dimension to absence reporting',
    submittedAt: '2026-08-05T12:00:00Z',
    submittedBy: 'S. Iyer (BA)',
    estimatedCostUsd: 12.4,
    riskLevel: 'low',
    evidenceSummary: { verified: 2, asserted: 0, failed: 0, coverageGaps: 0 },
    gates: [
      {
        id: 'g5',
        name: 'Business Owner',
        role: 'Finance Director',
        requiresEvidenceGrade: null,
        decision: 'approved',
        approver: 'K. Tan',
        approverEmail: 'k.tan@acme.example',
        decidedAt: '2026-08-05T13:20:00Z',
        comment: 'Looks right.',
        blockedBy: [],
        dueAt: '2026-08-05T12:00:00Z',
      },
      {
        id: 'g6',
        name: 'Platform Owner',
        role: 'HR Systems',
        requiresEvidenceGrade: 'verified',
        decision: 'pending',
        approver: null,
        approverEmail: null,
        decidedAt: null,
        comment: null,
        blockedBy: ['EV-3291 is flaky (34%) — flake rate above the 10% gate threshold'],
        dueAt: '2026-08-08T12:30:00Z',
      },
    ],
  },
  {
    id: 'ap-3',
    requirementId: 'req-5',
    requirementRef: 'MER-1017',
    title: 'Quarterly SOX evidence extract automation',
    submittedAt: '2026-07-23T10:30:00Z',
    submittedBy: 'S. Iyer (BA)',
    estimatedCostUsd: 31.5,
    riskLevel: 'medium',
    evidenceSummary: { verified: 1, asserted: 0, failed: 0, coverageGaps: 0 },
    gates: [
      {
        id: 'g7',
        name: 'Business Owner',
        role: 'Internal Audit',
        requiresEvidenceGrade: null,
        decision: 'approved',
        approver: 'D. Whitfield',
        approverEmail: 'd.whitfield@acme.example',
        decidedAt: '2026-07-23T14:00:00Z',
        comment: 'This removes two weeks of manual extract work per quarter.',
        blockedBy: [],
        dueAt: '2026-07-28T17:00:00Z',
      },
      {
        id: 'g8',
        name: 'Platform Owner',
        role: 'HR Systems',
        requiresEvidenceGrade: 'verified',
        decision: 'approved',
        approver: 'M. Okafor',
        approverEmail: 'm.okafor@acme.example',
        decidedAt: '2026-07-23T16:45:00Z',
        comment: 'Verified against the 2026R1 sandbox.',
        blockedBy: [],
        dueAt: '2026-07-29T17:00:00Z',
      },
      {
        id: 'g9',
        name: 'Release Manager',
        role: 'Change Advisory Board',
        requiresEvidenceGrade: 'verified',
        decision: 'approved',
        approver: 'L. Fontaine',
        approverEmail: 'l.fontaine@acme.example',
        decidedAt: '2026-07-24T09:15:00Z',
        comment: 'Scheduled for the 2026-07-26 release window.',
        blockedBy: [],
        dueAt: '2026-07-30T17:00:00Z',
      },
    ],
  },
]

/* ------------------------------------------------------------ audit chain */

export const AUDIT_ENTRIES: AuditEntry[] = [
  {
    id: 'au-14',
    seq: 4218,
    at: '2026-08-06T08:14:22Z',
    action: 'requirement.discussed',
    actor: 'R. Mensah',
    actorType: 'human',
    requirementRef: 'MER-1055',
    summary: 'Discussed shift differential scope; assistant raised 1 advisory dissent.',
    hash: 'a71f4c9e2b83d005',
    prevHash: '5c02de81ff37ab94',
    costUsd: 0.72,
    durationSeconds: 412,
    retention: 'ai_act',
    legalHold: false,
    workspaceId: 'ws-acme',
    ai: {
      model: 'claude-opus-5',
      modelVersion: '2026-07-14',
      promptHash: 'b2f4a19c7d3e08516ca2f7be40d19835cc71e2a04f6b8d3927ae5104cbf6320d',
      tokensIn: 24180,
      tokensOut: 1420,
      temperature: 0.2,
      groundedNodeIds: ['n-cfg-approval', 'n-bp-timeoff'],
    },
  },
  {
    id: 'au-13',
    seq: 4217,
    at: '2026-08-06T08:10:04Z',
    action: 'test.run',
    actor: 'Browser agent · claude-opus-5',
    actorType: 'agent',
    requirementRef: 'MER-1051',
    summary: 'EV-3310 started — asserted-grade run, push notification latency.',
    hash: '5c02de81ff37ab94',
    prevHash: 'e930aa17c4b26d1f',
    costUsd: 0.18,
    durationSeconds: 0,
    retention: 'ai_act',
    legalHold: false,
    workspaceId: 'ws-acme',
    ai: {
      model: 'claude-opus-5',
      modelVersion: '2026-07-14',
      promptHash: '77ac30be1f9d452e8b06cc31da7f5290e14b8f03a9d276cb5e18420df6ac9317',
      tokensIn: 8940,
      tokensOut: 610,
      temperature: 0.2,
      groundedNodeIds: ['n-scr-mobile'],
    },
  },
  {
    id: 'au-12',
    seq: 4216,
    at: '2026-08-05T17:40:11Z',
    action: 'approval.granted',
    actor: 'M. Okafor',
    actorType: 'human',
    requirementRef: 'MER-1042',
    summary: 'Platform Owner gate approved after reviewing 3 verified artifacts.',
    hash: 'e930aa17c4b26d1f',
    prevHash: '2b8814f0aa79c3e5',
    costUsd: 0,
    durationSeconds: 940,
    retention: 'sox',
    legalHold: true,
    workspaceId: 'ws-acme',
    reason: 'Verified evidence covers the approval-chain change; residual risk accepted in writing.',
  },
  {
    id: 'au-11',
    seq: 4215,
    at: '2026-08-05T16:12:47Z',
    action: 'approval.granted',
    actor: 'J. Almeida',
    actorType: 'human',
    requirementRef: 'MER-1042',
    summary: 'Business Owner gate approved.',
    hash: '2b8814f0aa79c3e5',
    prevHash: 'ff41029c7b6ad83e',
    costUsd: 0,
    durationSeconds: 320,
    retention: 'sox',
    legalHold: true,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-10',
    seq: 4214,
    at: '2026-08-05T15:00:02Z',
    action: 'approval.requested',
    actor: 'S. Iyer',
    actorType: 'human',
    requirementRef: 'MER-1042',
    summary: 'Submitted approval package with 4 gates.',
    hash: 'ff41029c7b6ad83e',
    prevHash: '77c3ba0e19f45d22',
    costUsd: 0,
    durationSeconds: 180,
    retention: 'sox',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-9',
    seq: 4213,
    at: '2026-08-05T14:31:58Z',
    action: 'policy.violated',
    actor: 'Meridian Policy Engine',
    actorType: 'system',
    requirementRef: 'MER-1042',
    summary: 'POL-004 blocked: RPT_APPR_AUDIT impacted with no verified regression coverage.',
    hash: '77c3ba0e19f45d22',
    prevHash: '19ae5c880b34f7d1',
    costUsd: 0,
    durationSeconds: 2,
    retention: 'sox',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-8',
    seq: 4212,
    at: '2026-08-05T14:19:33Z',
    action: 'test.run',
    actor: 'CI Runner',
    actorType: 'system',
    requirementRef: 'MER-1042',
    summary: 'EV-3304 failed after 3 attempts — mobile/web approval parity.',
    hash: '19ae5c880b34f7d1',
    prevHash: 'c48f7712ba09e6a3',
    costUsd: 0.36,
    durationSeconds: 96,
    retention: 'standard',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-7',
    seq: 4211,
    at: '2026-08-05T14:02:10Z',
    action: 'test.generated',
    actor: 'claude-opus-5',
    actorType: 'agent',
    requirementRef: 'MER-1042',
    summary: 'Generated 5 deterministic Playwright specs scoped to the impact set.',
    hash: 'c48f7712ba09e6a3',
    prevHash: '8e0b31ca9247fd50',
    costUsd: 3.41,
    durationSeconds: 288,
    retention: 'ai_act',
    legalHold: false,
    workspaceId: 'ws-acme',
    ai: {
      model: 'claude-opus-5',
      modelVersion: '2026-06-02',
      promptHash: 'd41f8c99a0b3e7526fa18cc4be03971d5a2e6408bb7f19c3d0e845a12f7c6b93',
      tokensIn: 41200,
      tokensOut: 6840,
      temperature: 0.2,
      groundedNodeIds: ['n-cfg-approval', 'n-rpt-audit', 'n-int-payroll'],
    },
  },
  {
    id: 'au-6',
    seq: 4210,
    at: '2026-08-01T09:31:20Z',
    action: 'impact.generated',
    actor: 'claude-opus-5',
    actorType: 'agent',
    requirementRef: 'MER-1042',
    summary: '5 impacted nodes, 1 coverage gap, 2 blind spots declared.',
    hash: '8e0b31ca9247fd50',
    prevHash: '61df20aa8c7b4913',
    costUsd: 2.86,
    durationSeconds: 94,
    retention: 'ai_act',
    legalHold: false,
    workspaceId: 'ws-acme',
    ai: {
      model: 'claude-opus-5',
      modelVersion: '2026-06-02',
      promptHash: '3a90ff17c28bd4650e1a7c93df20586b4cc8e1027ad9b63f5148e0ca29b7d431',
      tokensIn: 38600,
      tokensOut: 3120,
      temperature: 0.2,
      groundedNodeIds: ['n-cfg-approval', 'n-rpt-audit', 'n-int-payroll', 'n-bp-timeoff'],
    },
  },
  {
    id: 'au-5',
    seq: 4209,
    at: '2026-08-01T09:24:52Z',
    action: 'requirement.discussed',
    actor: 'J. Almeida',
    actorType: 'human',
    requirementRef: 'MER-1042',
    summary: 'Assistant raised blocking dissent; 3 options presented, option 1 accepted.',
    hash: '61df20aa8c7b4913',
    prevHash: '0a4c8817be3d92f6',
    costUsd: 1.33,
    durationSeconds: 692,
    retention: 'ai_act',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-4',
    seq: 4208,
    at: '2026-08-01T09:20:00Z',
    action: 'requirement.created',
    actor: 'J. Almeida',
    actorType: 'human',
    requirementRef: 'MER-1042',
    summary: 'Requirement raised from chat.',
    hash: '0a4c8817be3d92f6',
    prevHash: 'd117fa0c53b8e274',
    costUsd: 0,
    durationSeconds: 45,
    retention: 'standard',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-3',
    seq: 4207,
    at: '2026-08-01T06:15:00Z',
    action: 'source.synced',
    actor: 'Meridian Ingest',
    actorType: 'system',
    requirementRef: null,
    summary: 'Workday tenant re-indexed — 214 nodes changed, 8 links re-scored.',
    hash: 'd117fa0c53b8e274',
    prevHash: '93b0ce4471aa8f0d',
    costUsd: 1.92,
    durationSeconds: 1840,
    retention: 'standard',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-2',
    seq: 4206,
    at: '2026-07-24T09:15:00Z',
    action: 'change.deployed',
    actor: 'L. Fontaine',
    actorType: 'human',
    requirementRef: 'MER-1017',
    summary: 'Deployed to production in the 2026-07-26 window.',
    hash: '93b0ce4471aa8f0d',
    prevHash: '4f7ad3c018be95a1',
    costUsd: 0,
    durationSeconds: 60,
    retention: 'sox',
    legalHold: false,
    workspaceId: 'ws-acme',
  },
  {
    id: 'au-1',
    seq: 4205,
    at: '2026-07-21T15:30:00Z',
    action: 'approval.rejected',
    actor: 'D. Whitfield',
    actorType: 'human',
    requirementRef: 'MER-1028',
    summary: 'Rejected — contradicts SOX dual-approval control above $1k.',
    hash: '4f7ad3c018be95a1',
    prevHash: '00000000000000',
    costUsd: 0,
    durationSeconds: 540,
    retention: 'sox',
    legalHold: true,
    workspaceId: 'ws-acme',
    reason: 'Dual-approval control cannot be satisfied by a single signer under SOX ITGC.',
  },
]

/* ---------------------------------------------------------------- policy */

export const POLICIES: Policy[] = [
  {
    id: 'p1',
    ref: 'POL-001',
    name: 'No AI write access to production',
    description: 'Agents may read production but may only write to sandbox or dev environments.',
    severity: 'blocking',
    scope: 'All platforms',
    enabled: true,
    triggeredCount: 0,
  },
  {
    id: 'p2',
    ref: 'POL-004',
    name: 'Payroll-relevant changes require verified evidence',
    description:
      'Every impacted node on a payroll-relevant change must have at least one verified (deterministic) passing test. Asserted evidence does not satisfy this gate.',
    severity: 'blocking',
    scope: 'Workday HCM · Payroll',
    enabled: true,
    triggeredCount: 3,
  },
  {
    id: 'p3',
    ref: 'POL-007',
    name: 'Flake rate ceiling',
    description: 'Evidence with a flake rate above 10% cannot satisfy an approval gate.',
    severity: 'blocking',
    scope: 'All platforms',
    enabled: true,
    triggeredCount: 5,
  },
  {
    id: 'p4',
    ref: 'POL-011',
    name: 'Segregation of duties',
    description: 'The requester may not approve their own change at any gate.',
    severity: 'blocking',
    scope: 'All platforms',
    enabled: true,
    triggeredCount: 1,
  },
  {
    id: 'p5',
    ref: 'POL-014',
    name: 'Stale source warning',
    description:
      'Warn when an impact analysis relies on a source that has exceeded its staleness threshold.',
    severity: 'warning',
    scope: 'All sources',
    enabled: true,
    triggeredCount: 12,
  },
  {
    id: 'p6',
    ref: 'POL-020',
    name: 'PII field introduction review',
    description: 'Adding a PII field to any integration requires Data Privacy sign-off.',
    severity: 'blocking',
    scope: 'Integrations',
    enabled: true,
    triggeredCount: 0,
  },
]

/* ------------------------------------------------------------ analytics */

/**
 * Extraction activity for the demo workspace.
 *
 * Deliberately uneven — a failed run on Aug 06, a slow day on Aug 10 — because
 * a smooth series makes a dashboard look decorative. The shapes worth
 * designing for are the ones an operator reacts to.
 */
export const RUN_SERIES: RunPoint[] = [
  { date: 'Aug 04', runs: 3, failed: 0, nodes: 412, avgSeconds: 74.2 },
  { date: 'Aug 05', runs: 4, failed: 0, nodes: 508, avgSeconds: 69.8 },
  { date: 'Aug 06', runs: 5, failed: 2, nodes: 331, avgSeconds: 88.1 },
  { date: 'Aug 07', runs: 4, failed: 0, nodes: 476, avgSeconds: 71.5 },
  { date: 'Aug 08', runs: 6, failed: 1, nodes: 690, avgSeconds: 66.4 },
  { date: 'Aug 09', runs: 2, failed: 0, nodes: 254, avgSeconds: 61.9 },
  { date: 'Aug 10', runs: 5, failed: 0, nodes: 587, avgSeconds: 142.7 },
  { date: 'Aug 11', runs: 7, failed: 1, nodes: 803, avgSeconds: 70.3 },
  { date: 'Aug 12', runs: 6, failed: 0, nodes: 742, avgSeconds: 68.0 },
]

export const RUN_TOTALS: RunTotals = {
  runs: 42,
  succeeded: 38,
  failed: 4,
  nodes: 4803,
  totalSeconds: 3221.4,
  timedRuns: 41,
  avgSeconds: 78.6,
  llmUsd: 214.38,
  computeUsd: 66.12,
  tokensIn: 1_284_500,
  tokensOut: 218_940,
  operations: 168,
  days: 30,
}

export const COST_SERIES: CostPoint[] = [
  { date: 'Jun 09', llmUsd: 68, computeUsd: 22, changes: 4 },
  { date: 'Jun 16', llmUsd: 94, computeUsd: 31, changes: 6 },
  { date: 'Jun 23', llmUsd: 121, computeUsd: 38, changes: 7 },
  { date: 'Jun 30', llmUsd: 88, computeUsd: 27, changes: 5 },
  { date: 'Jul 07', llmUsd: 143, computeUsd: 44, changes: 9 },
  { date: 'Jul 14', llmUsd: 176, computeUsd: 52, changes: 11 },
  { date: 'Jul 21', llmUsd: 152, computeUsd: 47, changes: 10 },
  { date: 'Jul 28', llmUsd: 198, computeUsd: 61, changes: 13 },
  { date: 'Aug 04', llmUsd: 214, computeUsd: 66, changes: 14 },
]

export const CYCLE_TIME_SERIES: CycleTimePoint[] = [
  { week: 'Jun 09', baselineHours: 168, meridianHours: 142, changes: 4 },
  { week: 'Jun 16', baselineHours: 168, meridianHours: 128, changes: 6 },
  { week: 'Jun 23', baselineHours: 168, meridianHours: 121, changes: 7 },
  { week: 'Jun 30', baselineHours: 168, meridianHours: 104, changes: 5 },
  { week: 'Jul 07', baselineHours: 168, meridianHours: 96, changes: 9 },
  { week: 'Jul 14', baselineHours: 168, meridianHours: 88, changes: 11 },
  { week: 'Jul 21', baselineHours: 168, meridianHours: 81, changes: 10 },
  { week: 'Jul 28', baselineHours: 168, meridianHours: 74, changes: 13 },
  { week: 'Aug 04', baselineHours: 168, meridianHours: 71, changes: 14 },
]

export const DORA_METRICS: DoraMetric[] = [
  {
    label: 'Change failure rate',
    value: '4.2%',
    deltaPct: -38,
    direction: 'down_good',
    detail: 'vs 6.8% org baseline (trailing 90d)',
  },
  {
    label: 'Lead time for change',
    value: '71h',
    deltaPct: -58,
    direction: 'down_good',
    detail: 'request → signed-off, vs 168h baseline',
  },
  {
    label: 'Audit prep time',
    value: '3.5h',
    deltaPct: -91,
    direction: 'down_good',
    detail: 'per quarter, vs 40h manual baseline',
  },
  {
    label: 'Evidence completeness',
    value: '86%',
    deltaPct: 12,
    direction: 'up_good',
    detail: 'impacted nodes with verified coverage',
  },
]

export const MODEL_SPEND: ModelSpend[] = [
  { model: 'claude-opus-5', costUsd: 842.18, calls: 1284, share: 61 },
  { model: 'claude-sonnet-5', costUsd: 318.44, calls: 3902, share: 23 },
  { model: 'claude-haiku-4.5', costUsd: 124.9, calls: 12440, share: 9 },
  { model: 'Browser agent compute', costUsd: 96.32, calls: 218, share: 7 },
]
