/**
 * Helpers for the two things an audit entry needs beyond a summary sentence:
 * what actually changed (ALCOA+ / Part 11), and which model produced it
 * (EU AI Act Art. 12, NIST AI RMF traceability).
 */
import { sha256 } from './audit'
import type { AiProvenance, FieldChange, Id } from './types'

/* ---------------------------------------------------------------- diffing */

/** Render a value for the audit record without losing the fact it was empty. */
function display(value: unknown): string | null {
  if (value === null || value === undefined) return null
  if (Array.isArray(value)) return value.length ? value.join(', ') : '(empty)'
  if (typeof value === 'object') return JSON.stringify(value)
  const s = String(value)
  return s.length ? s : '(empty)'
}

/**
 * Field-level diff between two versions of a record.
 *
 * Only the fields named in `fields` are compared, because not every property
 * change is governance-relevant: bumping `updatedAt` on every save would bury
 * the one edit that mattered under noise. The caller decides what counts.
 */
export function diffFields<T extends object>(
  before: T,
  after: T,
  fields: { field: keyof T & string; label: string }[],
): FieldChange[] {
  const changes: FieldChange[] = []
  for (const { field, label } of fields) {
    const b = display(before[field])
    const a = display(after[field])
    if (b !== a) changes.push({ field, label, before: b, after: a })
  }
  return changes
}

/* ------------------------------------------------------------- provenance */

/**
 * The model the platform is currently pinned to.
 *
 * Pinned rather than "latest" on purpose: under Art. 12 a provider has to be
 * able to tell whether output came from a different system version, and that
 * question is unanswerable if the version floats. Changing this constant is a
 * substantial modification and should itself be an audited settings change.
 */
export const ACTIVE_MODEL = {
  model: 'claude-opus-5',
  modelVersion: '2026-07-14',
  temperature: 0.2,
} as const

/**
 * Build a provenance record for an AI-produced entry.
 *
 * The prompt is hashed rather than stored: the record needs to attest what the
 * input was without the audit log becoming a second copy of potentially
 * sensitive requirement text.
 */
export async function aiProvenance(input: {
  prompt: string
  tokensIn: number
  tokensOut: number
  groundedNodeIds?: Id[]
  model?: string
  modelVersion?: string
  temperature?: number
}): Promise<AiProvenance> {
  return {
    model: input.model ?? ACTIVE_MODEL.model,
    modelVersion: input.modelVersion ?? ACTIVE_MODEL.modelVersion,
    promptHash: await sha256(input.prompt),
    tokensIn: input.tokensIn,
    tokensOut: input.tokensOut,
    temperature: input.temperature ?? ACTIVE_MODEL.temperature,
    groundedNodeIds: input.groundedNodeIds ?? [],
  }
}

/* ----------------------------------------------------------- drift detection */

export interface ModelDrift {
  drifted: boolean
  generatedWith: string | null
  approvedUnder: string
  detail: string
}

/**
 * Whether an artefact was generated by a different model version than the one
 * now in force.
 *
 * This is the practical form of Art. 12's substantial-modification question. A
 * test plan approved under one model and re-run under another has not been
 * re-validated, and nobody would notice without this check — which is exactly
 * why the regulation asks for the version to be on the record.
 */
export function detectModelDrift(generatedWith: string | null | undefined): ModelDrift {
  const current = ACTIVE_MODEL.modelVersion
  if (!generatedWith) {
    return {
      drifted: false,
      generatedWith: null,
      approvedUnder: current,
      detail: 'No model version recorded against this artefact.',
    }
  }
  const drifted = generatedWith !== current
  return {
    drifted,
    generatedWith,
    approvedUnder: current,
    detail: drifted
      ? `Generated under ${generatedWith}; the platform now runs ${current}. Re-validation has not been recorded.`
      : `Generated and currently running under ${current}.`,
  }
}
