"""
The canonicalisation must agree with the frontend byte for byte.

`api/ledger/chain.canonicalise` is a port of `canonicalise()` in
`src/lib/audit.ts`. If the two drift, a chain written by one and verified by the
other reports tampering that did not happen — a false alarm on the one control
the product is built around, and one nobody would be able to explain.

The expected strings below were generated by running the actual TypeScript
implementation. They are checked in rather than recomputed so this test fails
if *either* side changes.
"""

from __future__ import annotations

from api.ledger.chain import canonicalise

GENESIS = "0" * 64


def test_minimal_entry():
    entry = {
        "seq": 1,
        "at": "2026-08-11T10:00:00Z",
        "action": "requirement.created",
        "actor": "Sathish Kumar",
        "actorType": "human",
        "requirementRef": "MER-1042",
        "summary": "Raised.",
        "prevHash": GENESIS,
        "costUsd": 0,
        "durationSeconds": 45,
        "retention": "standard",
        "legalHold": False,
        "workspaceId": "ws-acme",
    }
    assert canonicalise(entry) == (
        "12026-08-11T10:00:00Zrequirement.createdSathish KumarhumanMER-1042Raised."
        + GENESIS
        + "0.000045standardfalsews-acme"
    )


def test_cost_is_fixed_to_four_places():
    """JS `toFixed(4)`. An integer cost must render "1.5000", not "1.5"."""
    entry = {
        "seq": 2,
        "at": "2026-08-11T10:05:00Z",
        "action": "testcase.edited",
        "actor": "X",
        "actorType": "human",
        "requirementRef": None,
        "summary": "Edited.",
        "prevHash": "abc",
        "costUsd": 1.5,
        "durationSeconds": 0,
        "changes": [
            {"field": "state", "label": "State", "before": None, "after": "approved"}
        ],
        "reason": "why",
        "retention": "sox",
        "legalHold": True,
        "workspaceId": None,
    }
    result = canonicalise(entry)
    assert "1.5000" in result
    # A null `before` becomes a single space, so the absence of a prior value
    # is still committed to. Dropping it would let one be invented later.
    assert "state approved" in result
    assert result.endswith("soxtrue")


def test_ai_provenance_is_committed():
    entry = {
        "seq": 3,
        "at": "2026-08-11T10:09:00Z",
        "action": "requirement.discussed",
        "actor": "agent",
        "actorType": "agent",
        "requirementRef": "MER-1",
        "summary": "Turn.",
        "prevHash": "def",
        "costUsd": 0.27,
        "durationSeconds": 3,
        "ai": {
            "model": "claude-opus-5",
            "modelVersion": "2026-07-14",
            "promptHash": "deadbeef",
            "tokensIn": 19240,
            "tokensOut": 604,
            "temperature": 0.2,
            "groundedNodeIds": ["a", "b"],
        },
        "retention": "ai_act",
        "legalHold": False,
        "workspaceId": "ws-acme",
    }
    result = canonicalise(entry)
    assert "claude-opus-52026-07-14deadbeef19240604" in result
    assert "0.2a,b" in result


def test_integral_temperature_renders_like_javascript():
    """The divergence that would otherwise pass review unnoticed.

    JS `String(1)` is "1". Python `str(1.0)` is "1.0". A temperature of exactly
    1 would hash differently on the two sides while every fractional value
    agreed — so the chain would verify in testing and fail in production.
    """
    entry = {
        "seq": 4,
        "at": "2026-08-11T10:10:00Z",
        "action": "test.generated",
        "actor": "agent",
        "actorType": "agent",
        "requirementRef": None,
        "summary": "Gen.",
        "prevHash": "ghi",
        "costUsd": 0.5,
        "durationSeconds": 1,
        "ai": {
            "model": "m",
            "modelVersion": "v",
            "promptHash": "h",
            "tokensIn": 1,
            "tokensOut": 2,
            "temperature": 1,
            "groundedNodeIds": [],
        },
        "retention": "standard",
        "legalHold": False,
        "workspaceId": "ws",
    }
    result = canonicalise(entry)
    assert "mvh12" + "1" + "standard" in result
    assert "1.0" not in result
